# -*- coding: utf-8 -*-
"""motor.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1SUz-9tXIQMKF1LSAU_nbbv_v9Ej7bChr
"""

class Vehiculo:
  """This class represnt the structure of a vehicule"""

  def __init__(self, nombre_motor:str,peso_motor:int,potencia_motor:int, chasis:bool, modelo:str,fecha_de_fabricacion:str,tipo:str):
  #attributtes of the class Vehiculo
    self.nombre_motor = nombre_motor
    self.peso_motor = peso_motor
    self.potencia_motor = potencia_motor
    self.chasis = chasis
    self.modelo = modelo
    self.fecha_de_fabricacion = fecha_de_fabricacion
    self.tipo = tipo

  #define finctions of the class
  def get_motor(self):
    return "el nombre del motor es: "+self.nombre_motor + "    el peso del motor es: "+str(self.peso_motor)+ "    la potencia del motor es: "+str(self.potencia_motor)
  def get_chasis(self):
    return "el chasis es: "+ str(self.chasis)
  def get_modelo(self):
    return "el modelo es"+self.modelo
  def get_fecha_de_fabricacion(self):
    return "el año del vehiculo es: "+str(self.fecha_de_fabricacion)
  def get_tipo(self):
    return self.tipo
  def get_consumo(self):
    valor=0
    if self.chasis is True:
      valor=0.3
    else:
      valor=0.5
    cons=(1.1*self.potencia_motor + 0.2*self.peso_motor - valor)
    cons_=str(cons)
    return "el consumo de combustible es: "+ cons_



menu="""
Buen dia, es momento de crear su vehiculo:
Para crear un vehiculo digite 1
Para ver todos los vehiculos digite 2
"""
menu_2="""
que tipo de vehiculo desea crear
presione 1 para coche
presione 2 para camion
presione 3 para yate
presione 4 para motocicleta
presione 5 para salir
"""

#Menu

lista=[]
print(menu)

seleccion=int(input("seleccione una opcion: "))
if seleccion == 1:
  print(menu_2)
  respuesta=int(input("seleccione: "))

  if 0<(respuesta)<5:
    print("primero vamos a escoger el motor:")
    nombre_1=input("digite el nombre del motor: ")
    peso_1=int(input("digite el peso del motor: "))
    potencia_1=int(input("digite la potencia del motor: "))
    print("ahora el resto de partes del vehiculo")
    chasis_1=int(input(" para el chasis A digite 1, para el chasis B digite 0: "))
    print("ahora el modelo")
    modelo_1=input("escriba el modelo que desee: ")
    print("por ultimo el año del vehiculo")
    fecha_1=input("escriba el año cuando fue creado el vehiculo: ")
    if respuesta==1:
      tipo_1="coche"
    elif respuesta==2:
      tipo_1="camion"
    elif respuesta==3:
      tipo_1="yate"
    elif respuesta==4:
      tipo_1="moto"
    else:
      print("opcion invalida")
    vehiculo_2=Vehiculo(nombre_1,peso_1,potencia_1,chasis_1,modelo_1,fecha_1,tipo_1)
    lista.append(vehiculo_2)
    print("perfecto")
    print(menu_2)
    resultdado=int(input("seleccione una opcion"))
  print(menu)
  seleccion=int(input("seleccione una opcion: "))
for i in range(0,len(lista)):
  print(lista[i].get_motor())
  print(lista[i].get_chasis())
  print(lista[i].get_fecha_de_fabricacion())
  print(lista[i].get_modelo())
  print(lista[i].get_tipo())
  print(lista[i].get_consumo())